base_url = "https://praz.me"

title = "praz"
author = "praz"
generate_feeds = true
feed_filenames = ["atom.xml", "rss.xml"]

[markdown]
external_links_target_blank = true
external_links_no_referrer = true
